
    create table tb_equipamento (
       id int8 generated by default as identity,
        equipamento varchar(255),
        patrimonio varchar(255),
        id_setor_fk int8,
        primary key (id)
    );

    create table tb_ordem_de_servico (
       id int8 generated by default as identity,
        data_cadastro date,
        descricao_problema varchar(255),
        descricao_solucao varchar(255),
        prioridade varchar(255),
        status varchar(255),
        id_equipamento_fk int8,
        id_tecnico_fk int8,
        primary key (id)
    );

    create table tb_setor (
       id int8 generated by default as identity,
        coordenador varchar(255),
        email varchar(255),
        nome varchar(255),
        sigla varchar(255),
        telefone varchar(255),
        primary key (id)
    );

    create table tb_tecnico (
       id int8 generated by default as identity,
        email varchar(255),
        nome varchar(255),
        senha varchar(255),
        telefone varchar(255),
        primary key (id)
    );

    alter table if exists tb_equipamento 
       add constraint FKntlp1cajcpho9wie1ujt7avkb 
       foreign key (id_setor_fk) 
       references tb_setor;

    alter table if exists tb_ordem_de_servico 
       add constraint FK72i3rf4d0gegy3d0eji6pdsh9 
       foreign key (id_equipamento_fk) 
       references tb_equipamento;

    alter table if exists tb_ordem_de_servico 
       add constraint FKhb2wrn37t6n77nrhdaq8vtjo6 
       foreign key (id_tecnico_fk) 
       references tb_tecnico;
INSERT INTO TB_TECNICO (nome, telefone, email, senha) VALUES ('Marcelo Taz', '86876876', 'marcelo@gmail.com', '1234');
INSERT INTO TB_TECNICO (nome, telefone, email, senha) VALUES ('Bruno Mazeo', '86876876', 'bruno@gmail.com', '1234');
INSERT INTO TB_TECNICO (nome, telefone, email, senha) VALUES ('Claudia Raia', '86876876', 'claudia@gmail.com', '1234');
INSERT INTO TB_SETOR (sigla, nome, email, telefone, coordenador) VALUES ('CEREL', 'Central de Relaciomnamentos','cerel@gmail.com', '3409-6702','Adriano');
INSERT INTO TB_SETOR (sigla, nome, email, telefone, coordenador) VALUES ('DIREN', 'Direção de Ensino','diren@gmail.com', '3409-6703','Caio');
INSERT INTO TB_EQUIPAMENTO (equipamento, patrimonio, id_setor_fk) VALUES ('Notebook Lenovo', '12345', 1);
INSERT INTO TB_EQUIPAMENTO (equipamento, patrimonio, id_setor_fk) VALUES ('Daten AllInOne', '54321', 2);
INSERT INTO TB_ORDEM_DE_SERVICO (descricao_problema, descricao_solucao, data_cadastro, prioridade, status, id_tecnico_fk, id_equipamento_fk) VALUES ('Muito lento e não imprime', '', '2022-06-10', 'ALTA', 'PENDENTE', 1, 1);
INSERT INTO TB_ORDEM_DE_SERVICO (descricao_problema, descricao_solucao, data_cadastro, prioridade, status, id_tecnico_fk, id_equipamento_fk) VALUES ('Muito lento e não imprime', '', '2022-06-10', 'ALTA', 'PENDENTE', 1, 1);
